spring.application.name=backend

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://dpg-d6qeqo9j16oc73ell4m0-a.singapore-postgres.render.com:5432/sinh_vien_ci5b
spring.datasource.username=sinh_vien_ci5b_user
spring.datasource.password=erT9FWtXnufafEDrMhzsofSROgiQK5fH

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
